#!/usr/bin/env php
<?php
//author    : ding@gong.si
//created   : 2017/9/18 18:09
defined('APP_PATH') or define('APP_PATH', dirname(__FILE__));
if(PHP_SAPI !== 'cli'){
    exit('This script must run in Command Line Interface.');
}

include_once "config.php";

$config['autoload'] = ['common','vendor.autoload'];
$teaphp_autoroute = 'command';

require_once(APP_PATH.DIRECTORY_SEPARATOR."vendor/teaphp/framework/src/tea.php");


if(!empty($argv)){
    //这里解析一下命令,兼容 cmd:action 命令
    if(strpos($argv[1], ':') > 0){
        list($cmd, $action) = explode(':' , $argv[1]);
        unset($argv[0]);unset($argv[1]);
    }else{
        $cmd = $argv[1];
        $action = $argv[2];
        unset($argv[0]);unset($argv[1]);unset($argv[2]);
    }
    define('CMDARGS', array_values($argv));

    if(file_exists(APP_PATH.'/command/'.$cmd.'.php')){
        $command = load::classes('command.'.$cmd);
        $command->{$action}();
    }else{
        echo 'Command file not exist, Try again!';
    }
}else{
    echo 'Undefined command, Try again!';
}
die;


class command
{
    public $tea;
    public $db;
    public $session;

    function __construct()
    {
        global $tea;
        $this->tea = $tea;
        if(method_exists($this,'init')){
            $this->init();
        }
    }

    public static function run(){
    }
}